### ISSUE TITLE
that troublesome node dependency

### ISSUE THREAD

**Issue by biorisk** [axzilla/goilerplate-quickstart#1]
I love the idea and look of goilerplate, so I jumped into the quickstart. The Prerequisite section starts with Go (yay!), but then adds Node.js and npm (boo!) and make (meh). Is there a world where the goodness of CSS utility classes doesn't require sullying my pristine Go dev environment with any of the obnoxious javascript ecosystem? (Yes, this is a knee-jerk reaction ;-)

Excising Node and company might not be relevant to goilerplate's direction, but I could see backend devs gravitating toward the package for beautiful, easy to create internal tools if the requirements didn't involve js at all.

**Comment by axzilla** [comment]
Thank you for your feedback on Goilerplate! Your insights are really valuable.

* Do you think npm/Node is a real dealbreaker for many Go devs? I'm curious about your perspective.
* What's your concern with make? I've found it useful, but I'm open to alternatives.
* You're right, we can use Tailwind CLI without npm/Node. I'm considering this change, but we'd still need the tailwind.config.js file for customization.

I'm always looking to improve Goilerplate's accessibility. Any ideas on reducing dependencies without losing functionality? I'd love to hear your thoughts!

**Comment by biorisk** [comment]
Thanks for your response!

Just to answer your questions:
1. re:Node/npm. Backend Go devs that dip their toe into the JS world often get burnt by long build times and additional complexity. In Go, minimizing dependencies is idiomatic (and JS world is not a small dependency).
2. re: Make. Make isn't really a problem, just another dependency (and a common, respected one at that).
3. re: Tailwind. From a backend dev perspective, customizing tailwind.config.js AFTER I have my first working prototype doesn't sound too bad. Goilerplate looks good by default, so once I see it working, I can decide whether refinement is worth the time tradeoff.

**Comment by axzilla** [comment]
Makes sense. Thank you!
